// <auto-generated />
using System;
using ManufacturingOptimization.ProviderRegistry.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManufacturingOptimization.ProviderSimulator.Migrations
{
    [DbContext(typeof(ProviderSimulatorDbContext))]
    [Migration("20260303114509_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.DemoDataStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique();

                    b.ToTable("DemoDataStatus", (string)null);
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.EstimateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<double>("EmissionsKgCO2")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("TEXT");

                    b.Property<double>("QualityScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.ToTable("Estimates", (string)null);
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.ExecutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.ToTable("Executions", (string)null);
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.ExecutionScheduleSegmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.ToTable("ExecutionScheduleSegments", (string)null);
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.ProposalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArrivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeclineReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Process")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Proposals", (string)null);
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.EstimateEntity", b =>
                {
                    b.HasOne("ManufacturingOptimization.ProviderSimulator.Data.Entities.ProposalEntity", "Proposal")
                        .WithOne("Estimate")
                        .HasForeignKey("ManufacturingOptimization.ProviderSimulator.Data.Entities.EstimateEntity", "ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.ExecutionEntity", b =>
                {
                    b.HasOne("ManufacturingOptimization.ProviderSimulator.Data.Entities.ProposalEntity", "Proposal")
                        .WithOne("Execution")
                        .HasForeignKey("ManufacturingOptimization.ProviderSimulator.Data.Entities.ExecutionEntity", "ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.ExecutionScheduleSegmentEntity", b =>
                {
                    b.HasOne("ManufacturingOptimization.ProviderSimulator.Data.Entities.ExecutionEntity", "Execution")
                        .WithMany("ScheduleSegments")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.ProposalEntity", b =>
                {
                    b.OwnsOne("ManufacturingOptimization.ProviderSimulator.Data.Entities.MotorSpecificationsEntity", "MotorSpecs", b1 =>
                        {
                            b1.Property<Guid>("ProposalEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("AxisHeightMM")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CurrentEfficiency")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("MalfunctionDescription")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<double>("PowerKW")
                                .HasColumnType("REAL");

                            b1.Property<string>("TargetEfficiency")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("ProposalEntityId");

                            b1.ToTable("Proposals");

                            b1.WithOwner()
                                .HasForeignKey("ProposalEntityId");
                        });

                    b.Navigation("MotorSpecs")
                        .IsRequired();
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.ExecutionEntity", b =>
                {
                    b.Navigation("ScheduleSegments");
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.ProposalEntity", b =>
                {
                    b.Navigation("Estimate");

                    b.Navigation("Execution");
                });
#pragma warning restore 612, 618
        }
    }
}
